### ISSUE TITLE
💽 TikTok API

### ISSUE THREAD

**Issue by NatalieCampbellGit** [stanno03/Fridge-Fren#11]
- [ ] @NatalieCampbellGit 

https://developers.tiktok.com/doc/embed-videos/

Programmatically, you may convert a TikTok's video URL into embedded video markup by using the oEmbed API. It allows you to get the embed code and additional information about the video associated with the webpage link provided.

GET /oembed = Returns the embed code and information about the video

Param = Description 
url = The video link for embedding

Response 
The response format follows the specification of https://oembed.com/, please check it out for more details.

Example
Request URL

https://www.tiktok.com/oembed?url=https://www.tiktok.com/@scout2015/video/6718335390845095173

**Comment by AussieKing** [comment]
renounced. we got denied.
